### ISSUE TITLE
unitychan shaders do not work on unity 2021.3.1f1c1

### ISSUE THREAD

**Issue by andy380743909** [hecomi/uLipSync#32]
All materials are red, and can not update to URP
![image](https://user-images.githubusercontent.com/1617427/216341065-3a27d2f8-fe47-4ac5-875d-5f246670d414.png)

**Comment by andy380743909** [comment]
I know what's the problem. I created a new URP project and import this project into it. So the custom shader should upgrade to URP shader. I will find some documents about howto do the upgrade

**Comment by hecomi** [comment]
As you know, this is because the shader in Unity-chan doesn't support URP (and the automatic conversion). Supporting all rendering pipelines is not possible at the moment and I think it is not that important as this is just an example and you can easily check the lipsync behavior just by changing the shader of these materials. But if you have an idea how to easily convert the shader to support URP/HDRP, please let me know 🙏

**Comment by andy380743909** [comment]
I agree with you. The core function of this project is lip sync. Currently I have no ideas about how to convert the shaders to URP/HDRP. I am not expert of shader, but I'm learning about it, maybe it will take a long time to master it.
so let me close this issue.
