### ISSUE TITLE
Changes to AudioListener.volume affect mouth shape

### ISSUE THREAD

**Issue by Robert-Higgins** [hecomi/uLipSync#55]
Currently, when reducing AudioListener.volume, the lips move less and lip movement is exaggerated when increasing AudioListener.volume (for lip sync blend shapes). It appears the data in the OnAudioFilterRead is affected by the volume received by the audio listener.

Would it be possible to for the lip sync volume multiplier to be solely based on the AudioSource volume separate from the AudioListener? I am currently trying to implement a global volume slider, but lip sync is breaking due to this issue.

**Comment by Robert-Higgins** [comment]
*Update* A way around this is to just pass the audio through audio mixers which I probably should have been doing anyway.

**Comment by hecomi** [comment]
Sorry for the late reply. As an alternative, instead of changing the AudioSource volume, you can adjust the Output Sound Gain in uLipSync component.

<img width="481" alt="Screen Shot 2023-09-30 at 18 49 48" src="https://github.com/hecomi/uLipSync/assets/493433/6910cbad-52d2-4a0e-b538-36d761165bd6">
