### ISSUE TITLE
Compatability with Spine runtime?

### ISSUE THREAD

**Issue by LightningHyperBlaze45654** [hecomi/uLipSync#62]
The project's very good! The ability to detect vowels from live audio is amazing!
I'm currently trying to make project with spine runtime, and there seems no support with it. 
I may change the script, but i wonder this project will support spine.

**Comment by hecomi** [comment]
I apologize for the late response. If you want to directly manipulate joints instead of using BlendShapes, you can achieve this through the Animator mechanism.

- [uLipSync Animator Documentation](https://github.com/hecomi/uLipSync?tab=readme-ov-file#animator)

For more advanced control, it’s possible to create custom events.

- [uLipSync Custom Event Documentation](https://github.com/hecomi/uLipSync?tab=readme-ov-file#custom-event)

While I don’t have direct support for the spine, these methods might offer a viable alternative for your project.

**Comment by LightningHyperBlaze45654** [comment]
Just checked, modified the original code to solve this via directly modifying the spine bone's size.
